### ISSUE TITLE
`insert` function seems to be needlessly unsafe.

### ISSUE THREAD

**Issue by vi** [dbittman/non-overlapping-interval-tree#1]
Implementation uses `BTreeMap::insert`, which is safe.

Documentation states that a bad `NonOverlappingIntervalTree::insert` can lead to a corrupted tree, but it is not clear how a corrupted tree can lead to a memory unsafety / undefined behaviour.

**Comment by dbittman** [comment]
I was originally planning to implement things differently, and this got left behind, I suppose. I'll fix it when I'm back from vacation, or you can submit a PR if you like :)

**Comment by dbittman** [comment]
Fixed by [689ceb0](https://github.com/dbittman/non-overlapping-interval-tree/commit/689ceb06b7e6b7151b1e1a1957f80cd3d2f5601a)
